# Constants_Sequences_and_Random_Values

In [2]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [3]:
from datetime import date
date.today()

datetime.date(2019, 1, 14)

In [4]:
author = "kyubyong. https://github.com/Kyubyong/tensorflow-exercises"

In [5]:
tf.__version__

'1.2.1'

In [6]:
np.__version__

'1.11.1'

In [10]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Constant Value Tensors

Q1. Create a tensor of the shape [2, 3] with all elements set to zero.


In [5]:
import tensorflow as tf
print(tf.zeros([2,3]))

Tensor("zeros_3:0", shape=(2, 3), dtype=float32)


Q2. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to zero.

In [18]:
import numpy as np
import tensorflow as tf
_X = np.array([[1,2,3], [4,5,6]])
x = tf.convert_to_tensor(_X)
out = tf.zeros_like(x)
out.eval()

array([[0, 0, 0],
       [0, 0, 0]])

Q3. Create a tensor of shape [2, 3] with all elements set to one.

In [19]:
import tensorflow as tf
print(tf.ones([2,3]))
tf.ones([2,3]).eval()

Tensor("ones_4:0", shape=(2, 3), dtype=float32)


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

Q4. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to one.

In [20]:
_X = np.array([[1,2,3], [4,5,6]])
_x = tf.convert_to_tensor(_X)
out = tf.ones_like(_x)
out.eval()

array([[1, 1, 1],
       [1, 1, 1]])

Q5. Create a tensor of the shape [3, 2], with all elements of 5.

In [28]:
_X = np.full((3,2),5, dtype=int)
out = tf.convert_to_tensor(_X)
out.eval()

array([[5, 5],
       [5, 5],
       [5, 5]])

Q6. Create a constant tensor of [[1, 3, 5], [4, 6, 8]], with dtype=float32

In [32]:
out = tf.constant([[1, 3, 5], [4,6,8]], dtype=tf.float32)
out.eval()

array([[ 1.,  3.,  5.],
       [ 4.,  6.,  8.]], dtype=float32)

Q7. Create a constant tensor of the shape [2, 3], with all elements set to 4.

In [34]:
out = tf.constant(4, shape=[2,3])
out.eval()

array([[4, 4, 4],
       [4, 4, 4]])

## Sequences

Q8. Create a 1-D tensor of 50 evenly spaced elements between 5 and 10 inclusive.

In [35]:
out = tf.lin_space(5., 10. , 50)
out.eval()

array([  5.        ,   5.10204077,   5.20408154,   5.3061223 ,
         5.40816307,   5.51020432,   5.61224508,   5.71428585,
         5.81632662,   5.91836739,   6.02040815,   6.12244892,
         6.22448969,   6.32653046,   6.4285717 ,   6.53061247,
         6.63265324,   6.734694  ,   6.83673477,   6.93877554,
         7.04081631,   7.14285755,   7.24489784,   7.34693909,
         7.44897938,   7.55102062,   7.65306139,   7.75510216,
         7.85714293,   7.95918369,   8.06122494,   8.16326523,
         8.26530647,   8.36734676,   8.46938801,   8.5714283 ,
         8.67346954,   8.77551079,   8.87755108,   8.97959232,
         9.08163261,   9.18367386,   9.2857151 ,   9.38775539,
         9.48979568,   9.59183693,   9.69387817,   9.79591846,
         9.89795876,  10.        ], dtype=float32)

Q9. Create a tensor which looks like [10, 12, 14, 16, ..., 100].

In [39]:
out = tf.range(10, 101, 2)
out.eval()

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

## Random Tensors

Q10. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=2.

In [40]:
out = tf.random_normal([3, 2], mean=0, stddev=2)
out.eval()

array([[ 3.12313318, -1.42048013],
       [-0.52682197, -0.27576783],
       [ 2.89094996, -1.22082865]], dtype=float32)

Q11. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=1 such that any values don't exceed 2 standard deviations from the mean.

In [12]:
out = tf.truncated_normal([3, 2], mean=0, stddev=1)
out.eval()

array([[-0.08551561,  0.34900254],
       [-0.41675404, -0.63653308],
       [ 0.03393832, -0.78604704]], dtype=float32)

Q12. Create a random tensor of the shape [3, 2], with all elements from a uniform distribution that ranges from 0 to 2 (exclusive).

In [14]:
out = tf.random_uniform([3,2], maxval=2)
out.eval()

array([[ 0.50275159,  1.43186975],
       [ 1.48558235,  1.77635574],
       [ 1.4863348 ,  0.47371125]], dtype=float32)

Q13. Let X be a tensor of [[1, 2], [3, 4], [5, 6]]. Shuffle X along its first dimension.

In [19]:
out = tf.random_shuffle([[1, 2], [3, 4], [5, 6]])

[[1 2]
 [5 6]
 [3 4]]


Q14. Let X be a random tensor of the shape [10, 10, 3], with elements from a unit normal distribution. Crop X with the shape of [5, 5, 3].

[[[ -8.05899918e-01   2.72292346e-01   2.16315291e-03]
  [  2.74491131e-01   6.07317924e-01   1.76837713e-01]
  [  1.89213589e-01  -6.06034577e-01   1.14093232e+00]
  [  1.29428029e+00  -6.79318488e-01   1.25192130e+00]
  [ -2.18161201e+00   8.26316059e-01   2.24443465e-01]]

 [[ -4.31469619e-01   1.74119067e+00   8.67258251e-01]
  [ -1.04736495e+00   6.93329647e-02   2.46455050e+00]
  [  6.71136856e-01   1.38696265e+00   4.60413188e-01]
  [ -5.97481489e-01   1.32574654e+00   3.99490744e-01]
  [  1.16463304e+00  -2.86259800e-01   2.08924357e-02]]

 [[  1.16547585e+00   8.66836131e-01  -1.37871552e+00]
  [ -5.92198253e-01   4.10155028e-01   4.00556743e-01]
  [ -1.84391201e+00   6.03951514e-01   1.51700044e+00]
  [ -6.46995664e-01  -1.00076616e+00  -2.53373098e+00]
  [  1.11354995e+00  -4.37033147e-01  -1.22310674e+00]]

 [[ -1.24956787e-01   1.99593633e-01  -2.10244715e-01]
  [ -3.06440592e-01  -2.36029923e-01  -4.63652372e-01]
  [  7.61949897e-01   1.82299927e-01  -5.73334515e-01]
  [ 